# Generated by Django 3.2 on 2021-04-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength', models.IntegerField(default=60)),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.college')),
            ],
            options={
                'db_table': 'dept',
            },
        ),
    ]
