# Generated by Django 3.2 on 2021-04-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_Published',
            field=models.BooleanField(default=False),
        ),
    ]
